config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :users, only: [:new, :create]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :rooms, only: [:new, :index, :show, :create, :destroy] do
    resources :messages, only: [:create]
    resources :password_lock, only: [:index, :create]
  end
  
  get '*anything', to: 'errors#render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :body, presence: true
  after_create_commit {MessageBroadcastJob.perform_later self}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  validates :delete_password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  has_many :messages
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :signed_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def signed_in?
    current_user.present?
  end

  def sign_out
    session[:user_id] = nil
  end
  
  def already_sign_in
    redirect_to root_path if signed_in?
  end
  
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def render_404
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/password_lock_controller.rb
class PasswordLockController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
  end
  
  def create
    room = Room.find(params[:room_id])
    if room.join_password == password_lock_params[:join_password]
      session[:private_room] = room.id
      redirect_to room_path(room)
    else
      flash.now.alert = "パスワードが違います"
      render :index
    end
  end
  
  private
  def password_lock_params
    params.require(:password_lock).permit(:join_password)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :password_check, only: [:show]
  def new
    @room = Room.new
  end
  
  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = @room.messages.includes(:user).reverse
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      session[:private_room] = @room.id if @room.join_password.present?
      redirect_to room_path(@room)
    else
      flash.now.alert = "入力に誤りがあります"
      render :new
    end
  end
  
  def destroy
    room = Room.find(params[:id])
    if room.delete_password == delete_params[:password]
      room.destroy
      redirect_to root_path
    else
      @room = Room.find(params[:id])
      flash.now.alert = "パスワードが違います"
      render :show
    end
  end
  
  private
  def room_params
    params.require(:room).permit(:name, :join_password, :delete_password)
  end
  
  def delete_params
    params.require(:room).permit(:password)
  end
  
  def password_check
    if Room.exists?(id: params[:id]) 
      if Room.find(params[:id]).join_password.present?
        unless Room.find(params[:id]).id == session[:private_room]
          redirect_to room_password_lock_index_path(params[:id])
        end
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_sign_in, only: [:new]
  def new
  
  end
  
  def create
    user = User.find_by(name: session_params[:name])
    if user.present?
      if user.authenticate(session_params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash.now.alert = "入力に誤りがあります"
        render :new
      end
    else
      flash.now.alert = "入力に誤りがあります"
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
  private
  def session_params
    params.require(:session).permit(:name, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_sign_in, only: [:new]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user.errors.full_messages == ["Nameはすでに存在します"]
        flash.now.alert = "その名前は既に使われています"
      else
        flash.now.alert = "入力に誤りがあります"
      end
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/password_lock_helper.rb
module PasswordLockHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h3>メールアドレス無しで登録できる</br>チャットアプリです</h3>
<div class ="room-links">
  <%= link_to "ルーム一覧", rooms_path, class: "button bdblue" %>
  <%= link_to "ルーム作成", new_room_path, class: "button bdblue" %>
</div>

  <% if signed_in? %>
    <div class="login-status">
      <p><%= current_user.name %>さん ようこそ</p>
      <%= link_to "ログアウトする", logout_path, class: "button bred", method: :delete %>
    </div>
  <% else %>
    <div class="signin-signup-links">
      <%= link_to "ユーザー登録", new_user_path, class: "button brblue" %>
      <%= link_to "ログイン", login_path, class: "button bgreen" %>
    </div>
  <% end %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path do %>
    <h1>ChatApp</h1>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!-- エラーメッセージ -->
    <% if flash[:alert].present? %>
      <div class="alert-messsage bred">
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p>Name: <strong><%= message.user.name %></strong> <%= message.created_at.strftime('%Y/%m/%d %H:%M:%S') %> </p>
  <div class="message-body">
    <%= simple_format(h message.body) %>
  </div>
</div>

app/views/password_lock/index.html.erb
<h1>ルーム入場パスワード入力</h1>
<%= form_with scope: :password_lock, url: room_password_lock_index_path, local:true do |f| %>
  <table>
    <tbody>
      <tr>
        <td><%= f.label :join_password, "入場パスワード" %></td>
        <td><%= f.text_field :join_password, placeholder: "password" %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "入場する" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/rooms/index.html.erb
<%= link_to "<< トップに戻る", root_path %>
<h1>ルーム一覧</h1>

<table class="room-list-table">
  <thead>
    <th>ID</th>
    <th>部屋名</th>
    <th>メッセージ数</th>
    <th>パスワード</th>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <td><%= room.id %></td>
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.messages.length %></td>
      <td>
        <% if room.join_password.present? %>
          有
        <% else %>
          無
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1>チャットルームの新規作成</h1>

<%= form_with model: @room, url:rooms_path, local:true do |f| %>
  <table>
    <tbody>
      <tr>
        <td><%= f.label :name, "部屋名(必須)" %></td>
        <td><%= f.text_field :name, placeholder: "name"  %></td>
      </tr>
      <tr>
        <td><%= f.label :delete_password, "消去パスワード(必須)" %></td>
        <td><%= f.text_field :delete_password, placeholder: "delete_password"  %></td>
      </tr>
      <tr>
        <td><%= f.label :join_password, "部屋にパスワードをかける(任意)" %></td>
        <td><%= f.text_field :join_password, placeholder: "join_password"  %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "新規登録"  %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/rooms/show.html.erb
<%= link_to "<< 部屋一覧へ戻る", rooms_path %>
<div class="room-delete-form">
  <h4>部屋を消去する</h4>
  <%= form_with model: @room, method: :delete, data: { confirm: '本当に消しますか？' }, local:true do |f| %>
    <%= f.text_field :password, placeholder: "password" %>
    
    <%= f.submit "消去"  %>
  <% end %>
</div>
<h2>部屋名: <%= @room.name %></h2>
<h3>メッセージ↓</h3>
<div id="message-data">
  <% if @messages.present? %>
    <% @messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  <% end %>
</div>

<div class="message-form-space"></div>

<div class="message-form">
  <form>
    <input type="hidden" id="room_id" value="<%= @room.id %>">
    <% if signed_in? %>
      <textarea chat-data-behavior="room_speak" placeholder="メッセージ投稿フォーム" class="text-area" ></textarea>
      <input type="hidden" id="user_id" value="<%= current_user.id %>">
    <% else %>
      <div class="not-login">
        <p>メッセージを送るには会員登録が必要です</p>
        <%= link_to "ユーザー登録", new_user_path, class: "button brblue" %>
        <%= link_to "ログイン", login_path, class: "button bgreen" %>
      </div>
      
    <% end %>
  </form>
</div>

app/views/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= form_with model: @user, url: users_path, local:true do |f| %>
  <table>
    <tbody>
      <tr>
        <td><%= f.label :name, "ユーザー名" %></td>
        <td><%= f.text_field :name, placeholder: "name" %></td>
      </tr>
      <tr>
        <td><%= f.label :password, "パスワード" %></td>
        <td><%= f.password_field :password, placeholder: "password" %></td>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation, "パスワード(再入力)" %></td>
        <td><%= f.password_field :password_confirmation, placeholder: "password" %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "新規登録", class: "bigsubmit" %></td>
      </tr>
    </tbody>
  </table>
<% end %>